### ISSUE TITLE
Matrix.inverse is not correct in this case

### ISSUE THREAD

**Issue by dantecsm** [mathigon/fermat.js#80]
```javascript
import { Matrix } from "@mathigon/fermat";

var k = [[6.38342822594358e-17, 1.0424928665161133, -0.04249291867017746], [-1.0424928665161133, 0, 1], [0, 0, 1]];
var ik = Matrix.inverse(k);
console.log(Matrix.product(k, ik));
// expect [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
// got [[0.9999999999999999, 0, 0], [2.0849857330322266, 1, -0.04249286651611328], [0, 0, 1]]
```
![image](https://user-images.githubusercontent.com/35835538/147433640-9d157319-8c3d-4cd9-bb6c-7a99142d8f58.png)

**Comment by plegner** [comment]
Fixed in https://github.com/mathigon/fermat.js/commit/5d95e813df51066c3b524dd5c3277c3c0548084c, by treating numbers *very close* to 0 (e.g. `6e-17`) as *actually* 0, when performing Gaussian Elimination.

This avoids lost precision when calculating the inverse of these numbers (JavaScript integer overflow), but means that some matrices with lots of entries close to 0 will be treated as non-invertible.

Thanks for reporting this bug!
